### ISSUE TITLE
LIQ CONTAINER in shp files

### ISSUE THREAD

**Issue by Nocturnal42** [isms/circlemud-world-parser#1]
Came across this while working with the converted files. In shop files LIQ CONTAINER in the buy type field, is converted into

      {
        "namelist": "container",
        "note": "LIQ",
        "value": null
      }

When it is actually a different older name used for DRINKCON items, You can find an example of it in the circlemud perl script for converting shop files to 3.0 shop format.

It should convert to be

      {
        "namelist": null
        "note": "DRINKCON",
        "value": 17
      }

**Comment by isms** [comment]
@Nocturnal42 Thanks for reporting this, and sorry for the delay - not sure how I missed this. Do you happen to have a link to the perl script you mentioned?

**Comment by isms** [comment]
It's interesting, you can find documents all over the place that still reference `LIQ CONTAINER` but I agree it's the outdated version based on the most current documentation.

- DRINKCON example: https://github.com/Yuffster/CircleMUD/blob/master/doc/sources/building.tex#L624
- LIQ CONTAINER example: https://github.com/Yuffster/CircleMUD/blob/master/src/constants.c#L313

**Comment by isms** [comment]
@Nocturnal42 Should be fixed now
